### ISSUE TITLE
Splitting by every a few sentences, instead of just one?

### ISSUE THREAD

**Issue by anewbrand** [adueck/split-video-by-srt#1]
Is it possible to split a video by every a few sentences?
Current option only allows for splitting by each sentence's timestamp?

**Comment by adueck** [comment]
No, sorry, that would be very dificult to do automatically with a bash script. 😄 This tool is just for cutting videos up by timestamps. I found the easiest way to do that was to use [https://www.nikse.dk/subtitleedit](Subtitle Edit) to make a .srt file with all the sentences selected that you want. I hope it's still helpful for you.
